version: '3'

services:
#  diary:
#    build: .
#    restart: always
#    ports:
#      - 8888:3334
#    env_file:
#      - .env
  postgres:
    image: postgres:15.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 6655
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
